// Seed data for the UI prototype. There is no backend wired up yet — everything
// here is held in memory + localStorage via lib/store.js.

export const ROLES = {
  JOBSEEKER: "jobseeker",
  EMPLOYER: "employer",
  ADMIN: "superadmin",
};

export const MICRO_JOB_STATUSES = {
  OPEN: "open",
  CLOSED: "closed",
};

export const APPLICANT_STATUSES = {
  APPLIED: "applied",
  IN_PROGRESS: "in_progress",
  SUBMITTED: "submitted",
  APPROVED: "approved",
  REJECTED: "rejected",
  UPGRADED: "upgraded",
};

export const OFFER_STATUSES = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  DECLINED: "declined",
};

export const seedDatabase = {
  users: [
    {
      id: "u-admin",
      email: "admin@test.com",
      password: "test1234",
      role: ROLES.ADMIN,
      name: "Admin",
      createdAt: "2026-01-05T08:00:00Z",
      status: "active",
    },
    {
      id: "u-employer-1",
      email: "employer@test.com",
      password: "test1234",
      role: ROLES.EMPLOYER,
      name: "Marga Santos",
      companyName: "BrightHive Solutions",
      companyBlurb: "Remote-first SaaS studio building tools for LGUs.",
      verified: true,
      status: "active",
      createdAt: "2026-01-10T08:00:00Z",
    },
    {
      id: "u-employer-2",
      email: "hiring@cebutechworks.ph",
      password: "test1234",
      role: ROLES.EMPLOYER,
      name: "Rafael Uy",
      companyName: "Cebu TechWorks",
      companyBlurb: "Outsourced dev + QA teams for AU/US clients.",
      verified: true,
      status: "active",
      createdAt: "2026-01-14T08:00:00Z",
    },
    {
      id: "u-employer-3",
      email: "team@mangohealth.io",
      password: "test1234",
      role: ROLES.EMPLOYER,
      name: "Dana Reyes",
      companyName: "MangoHealth",
      companyBlurb: "Telehealth startup, Manila + Singapore.",
      verified: false,
      status: "active",
      createdAt: "2026-02-01T08:00:00Z",
    },
    {
      id: "u-jobseeker-1",
      email: "jobseeker@test.com",
      password: "test1234",
      role: ROLES.JOBSEEKER,
      name: "Juan Dela Cruz",
      headline: "Frontend Developer • React & Next.js",
      location: "Quezon City, NCR",
      skills: ["React", "Next.js", "Tailwind CSS", "AWS", "TypeScript"],
      bio: "3 years building customer dashboards. Learning cloud deploys via micro jobs.",
      discoverable: true,
      status: "active",
      createdAt: "2026-01-12T08:00:00Z",
    },
    {
      id: "u-jobseeker-2",
      email: "kim.alvarez@example.com",
      password: "test1234",
      role: ROLES.JOBSEEKER,
      name: "Kim Alvarez",
      headline: "Virtual Assistant • Customer Support",
      location: "Davao City",
      skills: ["Customer Support", "Zendesk", "Excel", "Email Handling"],
      bio: "Ex-BPO team lead, 5 years. Fast, accurate, night-shift ready.",
      discoverable: true,
      status: "active",
      createdAt: "2026-01-18T08:00:00Z",
    },
    {
      id: "u-jobseeker-3",
      email: "paolo.reyes@example.com",
      password: "test1234",
      role: ROLES.JOBSEEKER,
      name: "Paolo Reyes",
      headline: "Video Editor • Reels & YouTube",
      location: "Cebu City",
      skills: ["Premiere Pro", "After Effects", "Video Editing"],
      bio: "Editing short-form content for PH brands for 2 years.",
      discoverable: false,
      status: "active",
      createdAt: "2026-02-02T08:00:00Z",
    },
    {
      id: "u-jobseeker-4",
      email: "liza.tan@example.com",
      password: "test1234",
      role: ROLES.JOBSEEKER,
      name: "Liza Tan",
      headline: "Backend Developer • Node & AWS",
      location: "Pasig, NCR",
      skills: ["Node.js", "AWS", "PostgreSQL", "Docker"],
      bio: "Deploying side projects to AWS to build a public track record.",
      discoverable: true,
      status: "active",
      createdAt: "2026-02-10T08:00:00Z",
    },
  ],

  // "Try -> Prove -> Hire": short, paid tasks employers use as a paid audition.
  microJobs: [
    {
      id: "mj-1",
      employerId: "u-employer-1",
      title: "Fix one broken React date-picker component",
      category: "Web Development",
      description:
        "Our booking form's date-picker breaks on mobile Safari. Fix the component and submit a PR-style diff.",
      deliverable: "Link to the fixed component code + a short before/after clip.",
      pay: 1500,
      estimatedTime: "4 hours",
      skillsRequired: ["React", "CSS"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-10T03:00:00Z",
      moderation: "approved",
      applicants: [
        {
          jobseekerId: "u-jobseeker-1",
          status: APPLICANT_STATUSES.APPROVED,
          appliedAt: "2026-08-11T02:00:00Z",
          submission: {
            note: "Rewrote the date-picker with a controlled value and fixed the iOS Safari z-index bug.",
            link: "https://github.com/example/fix-datepicker/pull/12",
            submittedAt: "2026-08-11T09:00:00Z",
          },
          feedback: "Clean fix, tested it myself on an iPhone. Great work.",
          reviewedAt: "2026-08-12T01:00:00Z",
        },
      ],
    },
    {
      id: "mj-2",
      employerId: "u-employer-1",
      title: "Convert 40-page PDF report into an Excel workbook",
      category: "Data Entry",
      description:
        "We have a scanned PDF financial report. Need clean, formula-linked Excel tabs (no flattened numbers).",
      deliverable: "The .xlsx file with a short summary of tabs/formulas.",
      pay: 800,
      estimatedTime: "1 day",
      skillsRequired: ["Excel", "Data Entry"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-20T03:00:00Z",
      moderation: "approved",
      applicants: [
        {
          jobseekerId: "u-jobseeker-2",
          status: APPLICANT_STATUSES.SUBMITTED,
          appliedAt: "2026-08-21T02:00:00Z",
          submission: {
            note: "Workbook attached with 4 tabs, formulas linked, flagged 2 unreadable pages for review.",
            link: "https://drive.example.com/report.xlsx",
            submittedAt: "2026-08-22T05:00:00Z",
          },
        },
      ],
    },
    {
      id: "mj-3",
      employerId: "u-employer-2",
      title: "Edit one 60-second product reel",
      category: "Video Editing",
      description:
        "Raw clips + a voice-over track are ready. Need captions, jump cuts, and brand outro.",
      deliverable: "MP4 export + project file link.",
      pay: 1200,
      estimatedTime: "6 hours",
      skillsRequired: ["Video Editing", "Premiere Pro"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-24T03:00:00Z",
      moderation: "approved",
      applicants: [],
    },
    {
      id: "mj-4",
      employerId: "u-employer-2",
      title: "Answer 20 customer support emails (backlog clear-out)",
      category: "Customer Support",
      description:
        "Backlog of 20 tickets in Zendesk about shipping delays. Use our macros, escalate anything unusual.",
      deliverable: "20 tickets marked resolved/escalated with your notes.",
      pay: 600,
      estimatedTime: "3 hours",
      skillsRequired: ["Customer Support", "Zendesk"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-27T03:00:00Z",
      moderation: "approved",
      applicants: [
        {
          jobseekerId: "u-jobseeker-2",
          status: APPLICANT_STATUSES.UPGRADED,
          appliedAt: "2026-07-01T02:00:00Z",
          submission: {
            note: "Cleared all 20 tickets, flagged 3 for refund policy exceptions.",
            link: "https://zendesk.example.com/view/backlog-aug",
            submittedAt: "2026-07-01T08:00:00Z",
          },
          feedback: "Fastest turnaround we've had. Bringing her on part-time.",
          reviewedAt: "2026-07-02T01:00:00Z",
        },
      ],
    },
    {
      id: "mj-5",
      employerId: "u-employer-3",
      title: "Write one blog post: 'Telehealth in Rural PH'",
      category: "Writing",
      description: "800-1000 word blog post, SEO-friendly, casual but credible tone.",
      deliverable: "Google Doc link, ready to publish.",
      pay: 900,
      estimatedTime: "1 day",
      skillsRequired: ["Writing", "SEO"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-28T03:00:00Z",
      moderation: "pending",
      applicants: [],
    },
    {
      id: "mj-6",
      employerId: "u-employer-1",
      title: "Deploy a small Node API to AWS (ECS or Lambda)",
      category: "Web Development",
      description:
        "We have a working Node API locally. Need it containerized and deployed to AWS with a health check endpoint live.",
      deliverable: "Live URL + short writeup of the AWS setup.",
      pay: 3000,
      estimatedTime: "2 days",
      skillsRequired: ["Node.js", "AWS", "Docker"],
      status: MICRO_JOB_STATUSES.OPEN,
      createdAt: "2026-08-05T03:00:00Z",
      moderation: "approved",
      applicants: [
        {
          jobseekerId: "u-jobseeker-4",
          status: APPLICANT_STATUSES.APPROVED,
          appliedAt: "2026-08-06T02:00:00Z",
          submission: {
            note: "Deployed via ECS Fargate behind an ALB, health check green, added CloudWatch alarms.",
            link: "https://api.example-demo.com/health",
            submittedAt: "2026-08-08T10:00:00Z",
          },
          feedback: "Exactly what we needed. Want to talk contract work?",
          reviewedAt: "2026-08-09T02:00:00Z",
        },
      ],
    },
  ],

  // Standard full-time/part-time postings, kept lightweight since the
  // differentiators are the micro jobs + reverse hiring flows above.
  jobs: [
    {
      id: "job-1",
      employerId: "u-employer-1",
      title: "Frontend Developer (React)",
      type: "Full-time",
      location: "Remote (PH)",
      salaryRange: "₱45,000 - ₱65,000 / month",
      postedAt: "2026-08-15T03:00:00Z",
      applicants: 12,
      status: "open",
    },
    {
      id: "job-2",
      employerId: "u-employer-2",
      title: "Customer Support Specialist",
      type: "Part-time",
      location: "Cebu / Remote",
      salaryRange: "₱18,000 - ₱25,000 / month",
      postedAt: "2026-08-18T03:00:00Z",
      applicants: 27,
      status: "open",
    },
    {
      id: "job-3",
      employerId: "u-employer-3",
      title: "Backend Engineer (Node.js/AWS)",
      type: "Full-time",
      location: "Remote (PH)",
      salaryRange: "₱60,000 - ₱90,000 / month",
      postedAt: "2026-08-22T03:00:00Z",
      applicants: 8,
      status: "open",
    },
  ],

  // Powers "Reverse Hiring": employers search activity, not resumes.
  activity: [
    { id: "a-1", jobseekerId: "u-jobseeker-1", type: "micro_job_completed", skill: "React", title: "Fixed one React date-picker component", date: "2026-08-12T01:00:00Z" },
    { id: "a-2", jobseekerId: "u-jobseeker-1", type: "profile_update", skill: "TypeScript", title: "Added TypeScript to skill list", date: "2026-08-15T01:00:00Z" },
    { id: "a-3", jobseekerId: "u-jobseeker-4", type: "micro_job_completed", skill: "AWS", title: "Deployed a Node API to AWS ECS", date: "2026-08-09T02:00:00Z" },
    { id: "a-4", jobseekerId: "u-jobseeker-4", type: "skill_verified", skill: "Docker", title: "Verified Docker skill via employer review", date: "2026-08-09T02:05:00Z" },
    { id: "a-5", jobseekerId: "u-jobseeker-2", type: "micro_job_completed", skill: "Customer Support", title: "Cleared 20-ticket support backlog", date: "2026-07-02T01:00:00Z" },
    { id: "a-6", jobseekerId: "u-jobseeker-2", type: "upgraded", skill: "Customer Support", title: "Upgraded to part-time by Cebu TechWorks", date: "2026-07-02T01:00:00Z" },
    { id: "a-7", jobseekerId: "u-jobseeker-3", type: "profile_update", skill: "Video Editing", title: "Uploaded new reel to portfolio", date: "2026-08-01T01:00:00Z" },
  ],

  // Created when an employer approves a submission and offers to convert
  // the paid audition into an ongoing arrangement.
  offers: [
    {
      id: "off-1",
      microJobId: "mj-4",
      employerId: "u-employer-2",
      jobseekerId: "u-jobseeker-2",
      offerType: "Part-time",
      message: "You cleared the backlog faster than anyone else this month. Want to join us part-time?",
      status: OFFER_STATUSES.ACCEPTED,
      createdAt: "2026-07-02T01:30:00Z",
    },
    {
      id: "off-2",
      microJobId: "mj-6",
      employerId: "u-employer-1",
      jobseekerId: "u-jobseeker-4",
      offerType: "Contract",
      message: "Loved the AWS deploy. We have a 3-month contract lined up if you're interested.",
      status: OFFER_STATUSES.PENDING,
      createdAt: "2026-08-09T02:10:00Z",
    },
  ],

  // Mock escrow-style payments tied to micro jobs, for the admin dashboard.
  payments: [
    { id: "pay-1", microJobId: "mj-1", jobseekerId: "u-jobseeker-1", employerId: "u-employer-1", amount: 1500, status: "released", date: "2026-08-12T02:00:00Z" },
    { id: "pay-2", microJobId: "mj-4", jobseekerId: "u-jobseeker-2", employerId: "u-employer-2", amount: 600, status: "released", date: "2026-07-02T02:00:00Z" },
    { id: "pay-3", microJobId: "mj-6", jobseekerId: "u-jobseeker-4", employerId: "u-employer-1", amount: 3000, status: "released", date: "2026-08-09T03:00:00Z" },
    { id: "pay-4", microJobId: "mj-2", jobseekerId: "u-jobseeker-2", employerId: "u-employer-1", amount: 800, status: "in_escrow", date: "2026-08-22T05:30:00Z" },
  ],
};
